id: A7B814433
base_file: f969C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:01:40.586621
  last_modified_at: 2022-06-17 13:01:40.586624
