id: A7B814433
base_file: f20CA.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:01:40.581698
  last_modified_at: 2022-06-17 13:01:40.581706
